version: "3.9"  # optional since v1.27.0
services:
    moviesapp:
        build:
            context: client
            dockerfile: Dockerfile
        volumes:
            - '/app'
            - '/app/node_modules'
        ports:
            - "3000:3000"
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - moviesapi
    moviesapi:
        build: 
            context: service\MoviesService
            dockerfile: Dockerfile
        ports:
            - "36895:80"
